### ISSUE TITLE
Disable 'ADD' button if text feild is empty.

### ISSUE THREAD

**Issue by shubham7298** [aitoss/Web_Extension-todo#2]
If the text field is blank then a new work should not be added in the list, on pressing ENTER key or ADD button.
Try to disable 'ADD' button until text field is blank, also changing its color to light purple to show its disabled.

**Comment by satya9500** [comment]
I would like to resolve the issue.
I will be taking the value from the text box and comparing it with an empty string "" if it is so then i will leave the button disabled and if the match fails then in the else part i will replace the button code to enable it from my javascript file..

**Comment by satya9500** [comment]
I would also like to add a new feature to it where the date and time of work allocation was entered.

**Comment by shubham7298** [comment]
Issue resolved in #5
